title = 'The World of Water'
baseURL = 'https://alextruby.github.io/'
languageCode = 'en-us'
theme = 'ananke'


[pagination]
pagerSize = 3 # this is set low for demonstrating with dummy content. Set to a higher number

# languageDirection = 'rtl' for Right-To-Left languages


[languages.en]
contentDir = "content"
languageCode = 'en-US'
weight = 1
title = "Posts"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = "white"
author = "Alex Truby"
favicon = ""
site_logo = ""
description = "Explorations of water and travel."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = ""
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-center"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-black-30"
recent_posts_number = 3

[params.ananke.social.share]
networks = [
  "email",
  "linkedin"
]

[params.ananke.social.follow]
networks = [
  "linkedin"
]


[params.ananke.social.linkedin]
username = "alextruby"